spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alumnos
    username: root
    password: 56789
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true